package ru.atc.pgu.proccenter.stub.processingcenter;

import ru.atc.pgu.proccenter.stub.rev120315.BaseMessageType;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2
 * Mon Apr 06 20:46:20 MSK 2015
 * Generated source version: 2.2
 * 
 */
 
@WebService(targetNamespace = "http://pgu.gosuslugi.ru/ProcessingCenter", name = "ProcessingCenter")
@XmlSeeAlso({ru.atc.pgu.proccenter.stub.rev120528.ObjectFactory.class, ru.atc.pgu.proccenter.stub.include.ObjectFactory.class,ObjectFactory.class, ru.atc.pgu.proccenter.stub.rev120315.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ProcessingCenter {

    @WebResult(name = "registrationAndVoteResponse", targetNamespace = "http://pgu.gosuslugi.ru/ProcessingCenter", partName = "parameters")
    @WebMethod(action = "http://pgu.gosuslugi.ru/ProcessingCenter/registrationAndVote")
    public BaseMessageType registrationAndVote(
        @WebParam(partName = "parameters", name = "registrationAndVoteRequest", targetNamespace = "http://pgu.gosuslugi.ru/ProcessingCenter")
        BaseMessageType parameters
    );

    @WebResult(name = "dictionaryResponse", targetNamespace = "http://pgu.gosuslugi.ru/ProcessingCenter", partName = "parameters")
    @WebMethod(action = "http://pgu.gosuslugi.ru/ProcessingCenter/dictionary")
    public BaseMessageType dictionary(
        @WebParam(partName = "parameters", name = "dictionaryRequest", targetNamespace = "http://pgu.gosuslugi.ru/ProcessingCenter")
        BaseMessageType parameters
    );

    @WebResult(name = "regNumberResponse", targetNamespace = "http://pgu.gosuslugi.ru/ProcessingCenter", partName = "parameters")
    @WebMethod(action = "http://pgu.gosuslugi.ru/ProcessingCenter/regNumber")
    public BaseMessageType regNumber(
        @WebParam(partName = "parameters", name = "regNumberRequest", targetNamespace = "http://pgu.gosuslugi.ru/ProcessingCenter")
        BaseMessageType parameters
    );

    @WebResult(name = "searchParticipantsResponse", targetNamespace = "http://pgu.gosuslugi.ru/ProcessingCenter", partName = "parameters")
    @WebMethod(action = "http://pgu.gosuslugi.ru/ProcessingCenter/searchParticipants")
    public BaseMessageType searchParticipants(
        @WebParam(partName = "parameters", name = "searchParticipantsRequest", targetNamespace = "http://pgu.gosuslugi.ru/ProcessingCenter")
        BaseMessageType parameters
    );
}
